/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData photo_camera = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData add_circle_outline = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData live_tv = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData send = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart_empty = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData export_icon = IconData(0xf081, fontFamily: _kFontFam);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam);
  static const IconData paper_plane_empty = IconData(0xf1d9, fontFamily: _kFontFam);
}
